sudo: required
services:
  - docker

before_install:
  - docker build -t deqiu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true deqiu/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockertest_jesse"
  env: "Dockertestjesse-env"
  bucket_name: "elasticbeanstalk-us-east-1-992382645187"
  bucket_path: "dockertest_jesse"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  skip_cleanup: true
  #secret_access_key: "$AWS_SECRET_KEY"

#Dockerfile-env.eba-w4czv3vk.us-east-1.elasticbeanstalk.com