sudo: required
services:
  - docker

before_install:
  - docker build -t deqiu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true deqiu/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-2-992382645187"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  skip_cleanup: true
  #secret_access_key: "$AWS_SECRET_KEY"

#http://docker-react-env.eba-trm667in.us-east-2.elasticbeanstalk.com